// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0z7EGPKBoVwANlKY9pYJBhD6rsb-ium0',
    appId: '1:765104771590:web:a21c2edf1025052059e987',
    messagingSenderId: '765104771590',
    projectId: 'chatbot-3170c',
    authDomain: 'chatbot-3170c.firebaseapp.com',
    storageBucket: 'chatbot-3170c.firebasestorage.app',
    measurementId: 'G-EJ2NJ04BPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnD_i9z-gCjh4GXGoWYWrru65TGGLMhyE',
    appId: '1:765104771590:android:a282f6978700d41f59e987',
    messagingSenderId: '765104771590',
    projectId: 'chatbot-3170c',
    storageBucket: 'chatbot-3170c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl_trfnqbCPf-eBFBrExCwkJlb7qc9Zzc',
    appId: '1:765104771590:ios:a7287f4bb5c2eb2d59e987',
    messagingSenderId: '765104771590',
    projectId: 'chatbot-3170c',
    storageBucket: 'chatbot-3170c.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );
}
